name: dua
description: An example application for device_user_agent package.
publish_to: none
version: 1.0.0+2345678

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  device_user_agent:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
