name: device_user_agent
description: Flutter plugin to build user agent containing device information.
version: 0.1.2
repository: https://github.com/AcmeSoftwareLLC/device_user_agent
homepage: https://acmesoftware.com

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  package_info_plus: ^8.0.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
